3 module solutions
js-tasks-ru/jsbasic-20230629_mogvay-73 pull request #4
Opened 2023-07-15 22:35 UTC by Mogvay-web

2023-07-15 22:36 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-07-17 10:15 UTC, SinimaWath requested changes

2023-07-17 10:15 UTC, SinimaWath commented on 3-module/4-task/index.js
> +    arrFilter = arr.filter((item) => item !== "");
тут нужно поменять порядок и тогда не будет костылей в виде: ` item.age <= age` в map:
```
users.filter().map().join('\n')
```

2023-07-17 10:15 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  return user;
Тут проще без временной переменной: 

```
return {
  min: arrNumber[0],
  max: arrNumber.at(-1),
}
```

2023-07-17 14:49 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-07-22 19:19 UTC, SinimaWath approved these changes

2023-07-22 19:20 UTC, merged